# Basic
name:               "emredjan"
title:              A Journey in Data Science
email:              emredjan@gmail.com
author:             Emre Can
description:        "My journey to become a data scientist"
baseurl:            ""
url:                "http://emredjan.github.io"
date_format:        "%b %-d, %Y"
permalink:          pretty

# Markdown
# markdown:           rdiscount

# Navigation
nav:
  - name:           "About"
    href:           "/about"
  - name:           "LinkedIn"
    href:           "https://nl.linkedin.com/in/emrecan"
  - name:           "CV"
    href:           "/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
